### ISSUE TITLE
cart total works on local, undefined on live

### ISSUE THREAD

**Issue by hi-matbub** [hi-matbub/lg-coffee#114]
![Screen Shot 2020-11-26 at 9 32 08 AM](https://user-images.githubusercontent.com/53072963/100379743-4310b600-2fca-11eb-933d-3fee688ec686.jpg)

Not sure what's going on here.. appears to be a localStorage / state issue?

**Comment by hi-matbub** [comment]
it's an issue with state/ localstorage. everything is a mess right now. Solution here: https://github.com/hi-matbub/visionspeaks

**Comment by Orsunmigbare** [comment]
@hi-matbub ?  nice work here, but from what I can see, the stripe product API doesn't return a  price field object.

as seen in an example product object below :

```js
{ 
    id: 'prod_ISq1QieQlhiAxR',
    object: 'product',
    active: true,
    attributes: [],
    created: 1606435089,
    description: 'test shoelace',
    images: [],
    livemode: false,
    metadata: {},
    name: 'Shoe lace',
    statement_descriptor: null,
    type: 'service',
    unit_label: null,
    updated: 1606435089 
}
```
but in the code, the price is displayed with
```js
    ${formatUSD(cart[i].price)} USD
```
how about fetching individual prices for each product using  ?

```js
    stripe.prices.list()

**Comment by hi-matbub** [comment]
Hi @Orsunmigbare thanks for reaching out. It would be awesome to reach the prices the right way, up til now it's been a hacky metadata tag. See also #91


![Screen Shot 2020-11-26 at 5 02 05 PM](https://user-images.githubusercontent.com/53072963/100457273-95a7ac00-3076-11eb-8de2-c944723dc8d1.jpg)

As for the cart, thats a localStorage item that is built here: 

https://github.com/hi-matbub/lg-coffee/blob/a206c2efb90c9da21877ec6643ab6141d2d76f5d/packages/lg-init/lib/templates/og/lib/forms/add_to_cart/QtyControl.jsx#L24-L31

Sending the same `updatedCart` value to the top of the tree `handleUpdatedCartInState(updatedCart);` where it updates the state throughout the app. 

Atleast that's the idea.. I should be sending an PR to resolve this `undefined` issue later today but I would def want to avoid the unnecessary metadata tag. 

It sounds like you are on to something here and I'd love to roll with it!

**Comment by hi-matbub** [comment]
I'm going to be looking into the products price endpoint as my next priority here, As for now, issues related to this PR have been resolved
